services:
  db:
    image: postgres
    container_name: alvaaroDB
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: alvaroodb
    ports:
      - '5434:5432'
    volumes:
      - '/c/Users/saifu/Project/alvaaro-server/db_data'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

